server:
  port: 8080

# actuator monitor info
info:
  blog-url: http://dumasz.github.io
  author: dumas
  version: @project.version@

# loading all endpoints/default loading info / health
management:
  endpoints:
    web:
      exposure:
        include: '*'
      ## 路径映射，将 health 路径映射成 rest_health 那么在访问 health 路径将为404，因为原路径已经变成 rest_health 了，一般情况下不建议使用
      # path-mapping:
      #  health: rest_health
  endpoint:
    health:
      show-details: always
    # close specify endpoints
    shutdown:
      enabled: false
