server:
  port: 8081

spring:
  data:
    # MongoDB 配置项，对应 MongoProperties 类
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: admin
      username: root
      password: root

# 打印 mongodb 操作的具体语句。生产环境下，不建议开启
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG