server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root

# mybatis logger configuration
logging:
  level:
    com:
      dumas:
        sbta: DEBUG

# mapper configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dumas.sbta.mybatis
  configuration:
    map-underscore-to-camel-case: true

# commonMapper configuration
mapper:
  i-d-e-n-t-i-t-y: MYSQL
  mappers:
    - tk.mybatis.mapper.common.BaseMapper
  # 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: true
  # 枚举按简单类型处理
  enum-as-simple-type: true
# pagehelper configuration
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
