server:
  port: 8080

swagger:
  enable: true
  api-info:
    description: sbta-swagger
    license: sbta-swagger
    license-url: xx
    terms-of-service-url: xx
    title: sbta-swagger
    version: 1.0.0
    contact:
      name: dumas
      url: xx
      email: xx
  docket:
    base-package: com.dumas.sbta
    group-name: sbta-swagger

