server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  flyway:
    #若启动环境中的的数据库中有数据，但是没有flyway的历史表时，
    #false--启动会报错，true--继续生成flyway历史表完成脚本
    baseline-on-migrate: false
    # 执行时标记的tag 默认为<<Flyway Baseline>>
    baseline-description: <<Flyway Baseline>>
    # 是否启用flyway
    enabled: true
    # 检测迁移脚本的路径是否存在，如不存在，则抛出异常
    check-location: true
    # 脚本位置
    locations: classpath:db/migration
    # 在迁移时，是否校验脚本，假设V1.0__初始.sql已经迁移过了，在下次启动时会校验该脚本是否有变更过，则抛出异常
    validate-on-migrate: false