server:
  port: 8080

# actuator monitor info
info:
  blog-url: http://dumasz.github.io
  author: dumas
  version: @project.version@
  name: @project.artifactId@

# loading all endpoints/default loading info / health
management:
  endpoints:
    web:
      exposure:
        include: '*'
      ## 路径映射，将 health 路径映射成 rest_health 那么在访问 health 路径将为404，因为原路径已经变成 rest_health 了，一般情况下不建议使用
      # path-mapping:
      #  health: rest_health
      # 比较重要,默认 /actuator spring-boot-admin 扫描不到
      base-path: /
  endpoint:
    health:
      show-details: always
    # close specify endpoints
    shutdown:
      enabled: false

# 日志文件
logging:
  file:
    path: ./target/admin-server.log
