server:
  port: 8080

spring:
  rabbitmq:
    username: admin
    password: admin
    host: 127.0.0.1
    port: 5672
    virtual-host: my_vhost
    listener:
      simple:
        acknowledge-mode: manual