server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 只要依赖了 liquibase-core 默认可以不用做任何配置,但还是需要知道默认配置值是什么
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

